# Generated by Django 5.2.14 on 2026-05-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Оснащение',
                'verbose_name_plural': 'Оснащение',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('location', models.CharField(max_length=140, verbose_name='Локация')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('description', models.TextField(verbose_name='Описание')),
                ('approval_policy', models.CharField(choices=[('automatic', 'Автоматическое подтверждение'), ('manual', 'Ручное согласование')], default='automatic', max_length=16, verbose_name='Политика подтверждения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна для бронирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('equipment', models.ManyToManyField(blank=True, related_name='rooms', to='rooms.equipment', verbose_name='Оснащение')),
            ],
            options={
                'verbose_name': 'Переговорная',
                'verbose_name_plural': 'Переговорные',
                'ordering': ['name'],
            },
        ),
    ]
