# Generated by Django 5.2.14 on 2026-05-14 20:42

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Тема встречи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('timeslot', django.contrib.postgres.fields.ranges.DateTimeRangeField(verbose_name='Интервал бронирования')),
                ('participants_count', models.PositiveIntegerField(verbose_name='Количество участников')),
                ('status', models.CharField(choices=[('pending', 'Ожидает согласования'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=16, verbose_name='Статус')),
                ('moderation_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.meetingroom', verbose_name='Переговорная')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('participants_count__gte', 1)), name='booking_participants_count_gte_1'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), expressions=[(models.F('timeslot'), '&&'), (models.F('room'), '=')], name='prevent_active_booking_overlap')],
            },
        ),
    ]
